export const RECOMMENDED_JOBS = [
  {
    jobId: '1',
    jobTitle: 'Software Engineer',
    companyLogo:
      'https://pbs.twimg.com/profile_images/1605297940242669568/q8-vPggS_400x400.jpg',
    companyName: 'Google',
    specialization: 'Software',
    jobType: 'Full Time',
    minSalary: '5',
    maxSalary: '6',
    qualification: 'Bachelors in Computer Science ',

    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'We are looking for Software Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility',
    location: 'Banglore, Karnataka',
    experience: '2 Years',
    latitude: '12.971599',
    longitude: '77.594566',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
  {
    jobId: '2',
    jobTitle: 'Credit Analyst',
    qualification: 'Bachelors in Commerce ',
    companyLogo:
      'https://static.toiimg.com/thumb/msid-74887573,imgsize-66932,width-400,resizemode-4/74887573.jpg',
    companyName: 'Punjab National Bank',
    specialization: 'Finance',
    jobType: 'Full Time',
    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'The Credit Analyst will be responsible for ensuring all critical deadlines are met, completing their responsibilities as it pertains to completing loan disclosures, processing all loans timely and meeting established Service Level Agreement (SLAs). This position will also be responsible for maintaining exceptional communication with both internal and external customers/borrowers, and for taking the initiative to investigate, research and resolve any issues that may arise. Additionally, this individual will work closely with Sales, Underwriting, Valuation and Closing departments to ensure that all loan conditions are submitted timely, loan quality expectations are met, and that files move to closing with as few touches as possible',
    minSalary: '3',
    maxSalary: '4',
    location: 'Pune, Maharashtra',
    experience: '2 Years',
    latitude: '12.971599',
    longitude: '77.594566',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
  {
    jobId: '3',
    jobTitle: 'Software Tester',
    qualification: 'Bachelors in Computer Science ',
    companyLogo:
      'https://static.vecteezy.com/system/resources/previews/020/336/451/original/infosys-logo-infosys-icon-free-free-vector.jpg',
    companyName: 'Infosys',
    specialization: 'Developer',
    jobType: 'Full Time',
    latitude: '12.971599',
    longitude: '77.594566',
    minSalary: '6',
    maxSalary: '7',
    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'We are looking for a Full Stack Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility',
    location: 'Mumbai, Maharashtra',
    experience: '2 Years',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
];

export const DUMMY_PROFILE = {
  name: 'Shubham Vyavhare',
  email: 'shubham@gmail.com',
  gender: 'male',
  about: "Hello , I'm shubham and our team will win smart india hackathon",
  experience: [
    {
      id: '1',
      role: 'Credit Analyst',
      company: 'Bank of Baroda',
      from: 'Jan 2021',
      to: 'Dec 2023',
      empType: 'Full Time',
      description: 'Worked as a manager in bank of baroda for 2 years',
    },
  ],
  education: [
    {
      course: 'Bachelors in CSE',
      institute: 'Maharashtra Institue of Technology',
      major: 'Computer Science',
      from: 'Jun 2019',
      to: 'Mar 2023',
      description: 'This is education description',
    },
  ],
  skills: [
    'Javascript',
    'Python',
    'Java',
    'HTML',
    'ReactJS',
    'Redux',
    'Kotlin',
    'CSS',
    'Typescript',
    'DSA',
    'Docker',
  ],
  languages: ['English', 'Hindi', 'Marathi'],
  achievements: [
    {
      achievement: 'Employee of the year',
      organization: 'Bank of baroda',
      date: '22 Dec 2022',
      description: 'Got selected as best employee of 2022',
    },
    {
      achievement: 'Employee of the year',
      organization: 'Bank of baroda',
      date: 'Dec 22 2003',
      description: 'Got selected as best employee of 2022',
    },
  ],
};

export const DUMMY_JOBS = [
  {
    jobId: '1',
    jobTitle: 'Bank Manager',
    qualification: 'Bachelors in Commerce ',
    companyLogo:
      'https://static.toiimg.com/thumb/msid-74887573,imgsize-66932,width-400,resizemode-4/74887573.jpg',
    companyName: 'Punjab National Bank',
    specialization: 'Finance',
    jobType: 'Full Time',
    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'The Credit Analyst will be responsible for ensuring all critical deadlines are met, completing their responsibilities as it pertains to completing loan disclosures, processing all loans timely and meeting established Service Level Agreement (SLAs). This position will also be responsible for maintaining exceptional communication with both internal and external customers/borrowers, and for taking the initiative to investigate, research and resolve any issues that may arise. Additionally, this individual will work closely with Sales, Underwriting, Valuation and Closing departments to ensure that all loan conditions are submitted timely, loan quality expectations are met, and that files move to closing with as few touches as possible',
    minSalary: '9',
    maxSalary: '10',
    location: 'Pune, Maharashtra',
    experience: '2 Years',
    latitude: '12.971599',
    longitude: '77.594566',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
  {
    jobId: '2',
    jobTitle: 'Software Engineer',
    companyLogo:
      'https://pbs.twimg.com/profile_images/1605297940242669568/q8-vPggS_400x400.jpg',
    companyName: 'Google',
    specialization: 'Software',
    jobType: 'Full Time',
    minSalary: '5',
    maxSalary: '6',
    qualification: 'Bachelors in Computer Science ',

    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'We are looking for Software Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility',
    location: 'Banglore, Karnataka',
    experience: '2 Years',
    latitude: '12.971599',
    longitude: '77.594566',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
  {
    jobId: '3',
    jobTitle: 'Software Tester',
    qualification: 'Bachelors in Computer Science ',
    companyLogo:
      'https://static.vecteezy.com/system/resources/previews/020/336/451/original/infosys-logo-infosys-icon-free-free-vector.jpg',
    companyName: 'Infosys',
    specialization: 'Developer',
    jobType: 'Full Time',
    latitude: '12.971599',
    longitude: '77.594566',
    minSalary: '6',
    maxSalary: '7',
    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'We are looking for a Full Stack Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility',
    location: 'Mumbai, Maharashtra',
    experience: '2 Years',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
  {
    jobId: '4',
    jobTitle: 'Software Engineer',
    companyLogo:
      'https://pbs.twimg.com/profile_images/1605297940242669568/q8-vPggS_400x400.jpg',
    companyName: 'Google',
    specialization: 'Software',
    jobType: 'Full Time',
    minSalary: '5',
    maxSalary: '6',
    qualification: 'Bachelors in Computer Science ',

    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'We are looking for Software Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility',
    location: 'Banglore, Karnataka',
    experience: '2 Years',
    latitude: '12.971599',
    longitude: '77.594566',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
  {
    jobId: '5',
    jobTitle: 'Software Engineer',
    companyLogo:
      'https://pbs.twimg.com/profile_images/1605297940242669568/q8-vPggS_400x400.jpg',
    companyName: 'Google',
    specialization: 'Software',
    jobType: 'Full Time',
    minSalary: '5',
    maxSalary: '6',
    qualification: 'Bachelors in Computer Science ',

    requirements: [
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Meet customer service requirements through regular interactions with the customers to understand business condition, etc',
      'Generate leads by identifying potential industrial areas/trading units and prepare strategies.',
      'Assist the Credit Manager in unit inspections and ensure timely insurance renewal, DP updated, stock',
    ],
    description:
      'We are looking for Software Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility',
    location: 'Banglore, Karnataka',
    experience: '2 Years',
    latitude: '12.971599',
    longitude: '77.594566',
    facilities: [
      'Medical',
      'Dental',
      'Meal Allowance',
      'Transport Allowance',
      'Monday to Friday',
    ],
  },
];

export const DUMMY_NOTIFICATIONS = [
  {
    id: '1',
    logo: 'https://static.toiimg.com/thumb/msid-74887573,imgsize-66932,width-400,resizemode-4/74887573.jpg',
    title: 'Application Sent',
    description: 'Application to Punjab National Bank successfully sent',
    btnText: 'Application Details',
    timeAfterNotification: '1 min',
  },
  {
    id: '2',
    logo: 'https://store-images.s-microsoft.com/image/apps.60673.9007199266244427.4d45042b-d7a5-4a83-be66-97779553b24d.5d82b7eb-9734-4b51-b65d-a0383348ab1b?h=464',
    title: 'Twitter is Hiring',
    description: 'Twitter is currently hiring for role in you are interested',
    btnText: 'Apply Now',
    timeAfterNotification: '5 min',
  },
  {
    id: '3',
    logo: 'https://www.pngitem.com/pimgs/m/179-1793498_circle-image-job-alert-icon-png-transparent-png.png',
    title: '10+ Jobs Posted Today',
    description: 'Today 10+ jobs according to your interest posted',
    btnText: 'View Now',
    timeAfterNotification: '10 min',
  },
  {
    id: '4',
    logo: 'https://static.vecteezy.com/system/resources/previews/020/336/451/original/infosys-logo-infosys-icon-free-free-vector.jpg',
    title: 'Application Sent',
    description: 'Application to Infosys successfully sent',
    btnText: 'Application Details',
    timeAfterNotification: '1 min',
  },
  {
    id: '5',
    logo: 'https://store-images.s-microsoft.com/image/apps.60673.9007199266244427.4d45042b-d7a5-4a83-be66-97779553b24d.5d82b7eb-9734-4b51-b65d-a0383348ab1b?h=464',
    title: 'Twitter is Hiring',
    description: 'Twitter is currently hiring for role in you are interested',
    btnText: 'Apply Now',
    timeAfterNotification: '5 min',
  },
  {
    id: '6',
    logo: 'https://www.pngitem.com/pimgs/m/179-1793498_circle-image-job-alert-icon-png-transparent-png.png',
    title: '10+ Jobs Posted Today',
    description: 'Today 10+ jobs according to your interest posted',
    btnText: 'View Now',
    timeAfterNotification: '10 min',
  },
];
